spring.application.name=studentdb
server.port=8081

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password=amit12345678

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

email_api_key=67b430cfbae4131a2c34c7fbe5e58368